// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRYJ9xeqVnrGiAyY9c2ZN7_6HMaOamBho',
    appId: '1:623495199085:web:acbb335f9497c428700264',
    messagingSenderId: '623495199085',
    projectId: 'anniesbookbridge-daa70',
    authDomain: 'anniesbookbridge-daa70.firebaseapp.com',
    storageBucket: 'anniesbookbridge-daa70.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6Ni-jUh6NX3EfAyZ5vdVG9EgaqNIOZVU',
    appId: '1:623495199085:android:b1a48762aeb5a142700264',
    messagingSenderId: '623495199085',
    projectId: 'anniesbookbridge-daa70',
    storageBucket: 'anniesbookbridge-daa70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2XLzyaGWUcFwGI8WU4gJEESI7Lp3hODg',
    appId: '1:623495199085:ios:f5c72ddf095952d7700264',
    messagingSenderId: '623495199085',
    projectId: 'anniesbookbridge-daa70',
    storageBucket: 'anniesbookbridge-daa70.firebasestorage.app',
    iosBundleId: 'com.example.bookbridge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2XLzyaGWUcFwGI8WU4gJEESI7Lp3hODg',
    appId: '1:623495199085:ios:f5c72ddf095952d7700264',
    messagingSenderId: '623495199085',
    projectId: 'anniesbookbridge-daa70',
    storageBucket: 'anniesbookbridge-daa70.firebasestorage.app',
    iosBundleId: 'com.example.bookbridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRYJ9xeqVnrGiAyY9c2ZN7_6HMaOamBho',
    appId: '1:623495199085:web:ceb57db8775420bb700264',
    messagingSenderId: '623495199085',
    projectId: 'anniesbookbridge-daa70',
    authDomain: 'anniesbookbridge-daa70.firebaseapp.com',
    storageBucket: 'anniesbookbridge-daa70.firebasestorage.app',
  );
}
